color=090d13
font=Noto Sans
font-size=28
indicator-radius=90
indicator-thickness=8
inside-color=111820ee
inside-clear-color=1d3442ee
inside-ver-color=1d3442ee
inside-wrong-color=4c2028ee
key-hl-color=4dc5dc
bs-hl-color=ff7b85
ring-color=354354
ring-clear-color=4dc5dc
ring-ver-color=f4c66a
ring-wrong-color=ff7b85
text-color=e5edf2
text-clear-color=e5edf2
text-ver-color=e5edf2
text-wrong-color=e5edf2
show-failed-attempts
